[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Packages.composer", "nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["npm ci", "npm run build"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"